### ISSUE TITLE
Realizzare Landing Page

### ISSUE THREAD

**Issue by Byloth** [vuejsita/vuejsita.github.io#27]
Realizzare la home page del sito.

Dovrà fungere -in questa fase- da semplice landing page, con un aspetto accattivante e una semplice CtA che rimandi al canale Telegram (https://t.me/vue_ita).  
Proporrei -inoltre- di aggiungere altri link / bottoni social che rimandino alle altre pagine social di Vue.js Italia:

- Facebook: https://www.facebook.com/groups/997145120352550/
- GitHub: https://github.com/vuejsita/
- LinkedIn: https://www.linkedin.com/company/vuejsita/ <sup>[1]</sup>
- YouTube: https://www.youtube.com/@vuejsita <sup>[1]</sup>
- Twitter: https://twitter.com/vuejsita <sup>[1]</sup>

#### Piccola considerazione:
- Aggiungiamo anche un link alla documentazione ufficiale di Vue.js in Italiano (https://it.vuejs.org/)?

---

> 1. Al momento, pagina non attiva; da definire se aggiungere il link fin da subito.

**Comment by Byloth** [comment]
Ok: grazie a @jfet97, sono riuscito a ritrovare i riferimenti al canale YouTube. Aggiunti alla Issue.  
Ho -inoltre- cambiato anche il link della pagina LinkedIn, unificandola al resto dei canali social che abbiamo: `vuejsita`.

---

Un po' OT...  
Ma ti chiedo, @jfet97: può aver senso alllineare a questo standard anche il gruppo Telegram, ad un ipotetico [`@vuejsita`](https://t.me/vuejsita) anzichè [`@vue_ita`](https://t.me/vue_ita)?

**Comment by jfet97** [comment]
![Screenshot_2024-02-15-11-46-56-65_0b342c26d6c44f3c8d2de40eabb4e1da.jpg](https://github.com/vuejsita/vuejsita.github.io/assets/24520167/98b09a56-633c-4d05-a6e6-01efe83f1359)
